version: '3.5'

services:
  db:
    image: mysql:5.7
    #container_name: "mysql57"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER:     wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
      depends_on:
        - db
      image: wordpress:latest
      #container_name: "wordpress"
      volumes:
        - ./html:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      ports:
        - "8000:80"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME:     wordpress
        WORDPRESS_DB_USER:     wordpress
        WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #container_name: "phpmyadmin"
    restart: always
    depends_on:
      - db
    ports:
      - "8001:80"
volumes:
    db_data:
